title: <p align="center"> Prateek Anshul Srivastava </p>
logo: /assets/img/Userimage.PNG

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/prateekanshul/">LinkedIn</a> |
  <a href="https://github.com/prateekanshul">GitHub</a>
  
  <br>   
  I'm working on Big Data, Spark, Machine learning & NLP related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
